#!/bin/bash

set -e

cd "$(dirname "$0")"

versions=$(ls -1v releases/*.tar.gz | sed 's/.\{1,\}-\(.\{1,\}\)\.tar.gz/\1/' \
	| paste -sd ',' - | sed 's/,/, /g' | sed 's/\([0-9.]\{1,\}\)/"\1"/g')
sed -i -e "2s/\[.*\]/[$versions]/" releases.html
git add releases.html
