#!/usr/bin/perl

# Copyright (C) 2013 Simon Josefsson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use LWP::Simple;

use File::Basename;
use File::Temp qw/tempfile/;

my %categories = (
	'YubiCloud Servers' =>
	["https://raw.github.com/Yubico/yubikey-ksm/master/BLURB",
		"https://raw.github.com/Yubico/yubikey-val/master/BLURB"],
	'YubiKey Low-level Library' =>
	["https://raw.github.com/Yubico/yubico-c/master/BLURB",
		"https://raw.github.com/Yubico/yubico-j/master/BLURB"],
	'YubiKey NEO' =>
	["https://raw.github.com/Yubico/yubico-bitcoin-java/master/BLURB",
		"https://raw.github.com/Yubico/yubico-bitcoin-python/master/BLURB",
		"https://raw.github.com/Yubico/yubioath-android/master/BLURB",
		"https://raw.github.com/Yubico/ykneo-oath/master/BLURB",
		"https://raw.github.com/Yubico/yubitotp-android/master/BLURB",
		"https://raw.github.com/Yubico/yubioath-desktop/master/BLURB",
		"https://raw.github.com/Yubico/ykneo-openpgp/master/BLURB",
		"https://raw.github.com/Yubico/yubico-piv-tool/master/BLURB", ],
	'YubiKey Personalization' =>
	["https://raw.github.com/Yubico/yubikey-personalization/master/BLURB",
		"https://raw.github.com/Yubico/yubikey-personalization-gui/master/BLURB",
		"https://raw.github.com/Yubico/libykneomgr/master/BLURB",
		"https://raw.github.com/Yubico/yubikey-neo-manager/master/BLURB"],
	'YubiKey Integration' =>
	["https://raw.github.com/Yubico/yubico-pam/master/BLURB",
		"https://raw.github.com/Yubico/rlm-yubico/master/BLURB",
		"https://raw.github.com/Yubico/yubiauth/master/BLURB",
		"https://raw.github.com/Yubico/yubix/master/BLURB",
		"https://raw.github.com/Yubico/yubico-windows-auth/master/BLURB"],
	'YubiHSM projects' =>
	["https://raw.github.com/Yubico/python-pyhsm/master/BLURB"],
	'YubiCloud Clients' =>
	["https://raw.github.com/Yubico/yubico-java-client/master/BLURB",
	"https://raw.github.com/Yubico/yubico-c-client/master/BLURB",
	"https://raw.github.com/Yubico/php-yubico/master/BLURB",
	"https://raw.github.com/Yubico/yubico-perl-client/master/BLURB",
	"https://raw.github.com/Yubico/yubico-dotnet-client/master/BLURB"],
   );


my $html;

foreach my $category (keys %categories) {
    my @blurbs = @{$categories{$category}};
    $html .= "<h2>$category</h2>\n\n";
    $html .= "<p><table>\n<tr><th>Project name</th><th>License</th>" .
	"<th>Description</th></tr>\n\n";
    foreach my $blurb (@blurbs) {
	my ($homepage, $license, $project, $summary, $name);
	my $content = get($blurb);
	$homepage = $1 if $content =~ m,Homepage: (.+),g;
	$license = $1 if $content =~ m,License: (.+),g;
	$name = $1 if $content =~ m,Name: (.+),g;
	$project = $1 if $content =~ m,Project: (.+),g;
	$summary = $1 if $content =~ m,Summary: (.+),g;
	die "could not parse blurb: $content ($blurb)"
	    if !$project || !$summary || !$license;
	$name = $project unless $name;
	$html .= "<tr><td><a href=\"$homepage\">$project</a></td>\n";
	$html .= "<td><a href=\"http://spdx.org/licenses/$license\">" .
	    "$license</a></td>\n";
	$html .= "<td>$summary</td></tr>\n\n";
	if($homepage =~ m,opensource\.yubico\.com,) {
    system(dirname($0) . "/build-projectpage $project");
	}
    }
    $html .= "</table></p>\n";
}

my $indexhtml = do { local $/; <> };
$indexhtml =~ s/REPLACEME/$html/g;
print $indexhtml;
