#!/usr/bin/python

import os
from requests import get


BLURB_TEMPLATE = """Author: Yubico
Basename: %(name)s
Homepage: http://opensource.yubico.com/%(name)s/
License: %(license)s
Name: %(name)s
Project: %(name)s
Summary: %(description)s"""


def get_license():
    try:
        with open('COPYING', 'r') as f:
            copying = f.read()
            if 'Redistribution and use in source and binary forms, with or' \
                    in copying:
                return 'BSD-2-Clause'
            if 'Apache License' in copying:
                return 'Apache-2.0'
    except Exception as e:
        print e
        print 'No COPYING file!'
    return 'UNKNOWN_LICENSE'


def main():
    if os.path.isfile('BLURB'):
        print 'BLURB file already exists!'
        return

    parts = None
    with os.popen('git remote -v | grep github | grep fetch') as f:
        parts = f.read().split()
    url = parts[1]
    name = url.split('/')[1].split('.git')[0]
    api_url = 'https://api.github.com/repos/Yubico/%s' % name
    print 'Fetching: %s' % api_url
    data = get(api_url).json()

    blurb = BLURB_TEMPLATE % {
        'name': data['name'],
        'description': data['description'],
        'license': get_license()
    }

    with open('BLURB', 'w') as f:
        f.write(blurb)

    os.popen('git add BLURB')

    print 'BLURB written! Make sure it is OK!'
    print
    print blurb
    print
    print 'If satisfied:'
    print 'git commit -m "Added BLURB" && git push'


if __name__ == '__main__':
    main()
